skip_tags: true

branches:
  except:
    - gh-pages
    - built
  
matrix:
    fast_finish: true

image: Visual Studio 2017

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017"
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

configuration:
  - Debug
  - Release
  
install:
  - cmd: git submodule update --init --recursive
  
before_build:
  - mkdir _bld
  - cd _bld
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=%configuration% -DCSTE_MATH_BUILD_TESTS=ON -DCSTE_MATH_BUILD_SINGLE_HEADER=ON ..

build:
  project: _bld\cste_math.sln
 
test_script:
  - cmd: ctest -C %configuration% -VV
