language: cpp

dist: xenial

branches:
  except:
  - gh-pages
  - single_header

env:
  - DELAYED_EVAL="CC=gcc-7 && CXX=g++-7"
      
addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - g++-7

before_install:
  - eval "${DELAYED_EVAL}"

script:
    - mkdir _bld && cd _bld
    - cmake -DCMAKE_BUILD_TYPE=DEBUG -DCSTE_MATH_BUILD_TESTS=ON -DCSTE_MATH_BUILD_SINGLE_HEADER=ON ..
    - cmake --build .
    - ctest --output-on-failure
    - cd ..
    - mkdir _bld_rel && cd _bld_rel
    - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCSTE_MATH_BUILD_TESTS=ON -DCSTE_MATH_BUILD_SINGLE_HEADER=ON ..
    - cmake --build .
    - ctest --output-on-failure

notifications:
  email: false
