workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    environment:
      - DOCS_BRANCH: gh-pages
      - BUILT_BRANCH: built
      - GH_EMAIL: francois.chabot.dev+vecppci@gmail.com
      - GH_NAME: VecppCI

    steps:
      - checkout
      - run: git submodule update --init
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install mkdocs
            mkdocs --version
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-
          paths:
            - "venv"
      - run:
          name: build docs
          command: |
            . venv/bin/activate
            mkdocs build
      - run:
          name: build single header
          command: |
            . venv/bin/activate
            cd include
            python3 ../tools/header_compiler/header_compiler.py --output=cste_math/cste_math_single.h --notice=../misc/notice.txt --header_guard="CSTE_MATH_SINGLE_INCLUDE_H_" --input=cste_math/cste_math.h

      - deploy: # run tests
          name: deploy docs
          command: |            
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

            git clone $CIRCLE_REPOSITORY_URL out

            cd out
            git checkout $DOCS_BRANCH || git checkout --orphan $DOCS_BRANCH
            git rm -rf .
            cd ..

            cp -a site/. out/.

            mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
            cp .appveyor.yml ./out/
            cd out

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

            git push origin $DOCS_BRANCH

      - deploy: # run tests
          name: deploy built
          command: |            
            cd out
            git checkout $BUILT_BRANCH || git checkout --orphan $BUILT_BRANCH
            git rm -rf .
            cd ..

            cp -a include/. out/.

            mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
            cp .appveyor.yml ./out/
            cd out

            git add -A
            git commit -m "Automated deployment to Built Lib: ${CIRCLE_SHA1}" --allow-empty

            git push origin $BUILT_BRANCH